### PR TITLE
Add new metadata fields

### PR DESCRIPTION
**Pull request by dannyglover**
Added support for the following fields (dart field names):

* `albumArtist`
* `discNumber`
* `discTotal`

Changed fields:

* `artist` > `trackArtist`

### CODE REVIEW

**Comment by dannyglover** [comment]
I will be adding to this PR until I've implemented all of the fields I requested in https://github.com/erikas-taroza/audiotags/issues/9

Once you're happy with the PR, please don't merge until I comment here stating that I am finishing implementing this PR in its entirety.

**Comment by erikas-taroza** [comment]
> I will be adding to this PR until I've implemented all of the fields I requested in #9
> 
> Once you're happy with the PR, please don't merge until I comment here stating that I am finishing implementing this PR in its entirety.

I will make this a draft PR. You can then mark it as ready to review when you are done.

**Comment by dannyglover** [comment]
I revised my feature request requirements due to producer and language barely being featured in any of my commercial music library (and lofty throwing errors for them with certain file formats).

I still want the `originalReleaseDate` field, but I'm going to have to leave that one to you.

**Review by erikas-taroza — APPROVED** [review]
LGTM

**Pull request merged**
